### ISSUE TITLE
Try to receive call on iOS but not sure how

### ISSUE THREAD

**Issue by Rubinhuang9239** [joseph-onsip/sipjs-cordova#19]
Hi guys, I'm trying to use sipjs-cordova to build an Cordova App to  Cordova App Webrtc communication, just tryout the call from App to Browser and it looks great.

But when I tried assign my uri, authUsername and password to my App it seems not working anymore.
I'm not sure if my code is on the right way to do that.

//------New_SIP.UA------//

window.ua = new SIP.UA({
        mediaHandlerFactory: PhoneRTCMediaHandler,
        traceSip: true,
        displayName: 'myDisName',
        uri: 'name@domain.com',
        authorizationUser: 'authUserName',
        password: '*****'
      });

Thanks!

**Comment by joseph-onsip** [comment]
closing in favor of https://github.com/onsip/onsip-cordova/issues/22
